import { state } from './state.js';
import { saveState } from './storage.js';
import { escapeHtml, formatTopic, capitalize } from './utils.js';
import { BANK, TENSES, VOCAB } from './data.js';
import { recordIncorrectQuestion } from './review.js';

export function renderTenses() { const grid = document.getElementById('tenseGrid'); if (!grid) return; grid.innerHTML = TENSES.map((tense, index) => `<div class="card tense-card ${state.openTense === index ? 'open' : ''}" data-tense-index="${index}"><div class="tc-top"><div><div class="tc-aspect">${escapeHtml(tense.aspect)}</div><h4>${escapeHtml(tense.name)}</h4></div><span class="chev">▼</span></div><div class="tc-formula">${escapeHtml(tense.formula)}</div><div class="tense-detail" style="max-height:${state.openTense === index ? '420px' : '0px'}"><div class="tense-detail-inner"><ul>${tense.uses.map(use => `<li>${escapeHtml(use)}</li>`).join('')}</ul><div class="tc-examples">${tense.ex.map(example => `<div class="tc-example">${escapeHtml(example)}</div>`).join('')}</div></div></div></div>`).join(''); grid.querySelectorAll('[data-tense-index]').forEach(card => card.addEventListener('click', () => { state.openTense = Number(card.dataset.tenseIndex) === state.openTense ? null : Number(card.dataset.tenseIndex); renderTenses(); })); }

export function renderVocabulary() { const grid = document.getElementById('vocabGrid'); const tabs = document.getElementById('vocabCategoryTabs'); if (!grid || !tabs) return; const categories = Object.keys(VOCAB); const category = tabs.dataset.active || categories[0]; tabs.innerHTML = categories.map(cat => `<button class="pill ${cat === category ? 'active' : ''}" data-vocab-cat="${escapeHtml(cat)}">${escapeHtml(cat)}</button>`).join(''); grid.innerHTML = (VOCAB[category] || []).map((item, index) => `<div class="flashcard" data-flip="${index}"><div class="flashcard-inner"><div class="flashcard-face flashcard-front"><div class="word">${escapeHtml(item.w)}</div><div class="pos">${escapeHtml(item.p)}</div></div><div class="flashcard-face flashcard-back"><div class="mean">${escapeHtml(item.m)}</div><div class="ex">${escapeHtml(item.e)}</div></div></div></div>`).join(''); tabs.querySelectorAll('[data-vocab-cat]').forEach(btn => btn.addEventListener('click', () => { tabs.dataset.active = btn.dataset.vocabCat; renderVocabulary(); })); grid.querySelectorAll('.flashcard').forEach(card => card.addEventListener('click', () => card.classList.toggle('flipped'))); }

function poolForCurrentSelection() { const { selectedTopic: topic, selectedDifficulty: difficulty } = state; if (topic === 'mixed') return Object.keys(BANK).flatMap(key => (BANK[key][difficulty] || []).map(q => ({ ...q, topic: key, difficulty }))).sort(() => Math.random() - 0.5); const topicBank = BANK[topic] || BANK.tenses; return (topicBank[difficulty] || topicBank.intermediate).map(q => ({ ...q, topic, difficulty })); }

export function startQuickQuiz() { state.quiz = { questions: poolForCurrentSelection().slice(0, 6), current: 0, score: 0, isReviewMode: false }; renderQuiz(); }

export function renderQuiz() { const playArea = document.getElementById('quizPlayArea'); if (!state.quiz || !playArea) return; const q = state.quiz.questions[state.quiz.current]; if (!q) { const total = state.quiz.questions.length; const score = total ? Math.round(state.quiz.score / total * 100) : 100; const xp = Math.max(5, Math.round(score / 10)); playArea.innerHTML = `<div class="card quiz-results"><div class="score">${score}%</div><div class="xp-earned">+${xp} XP</div><button class="btn btn-primary" id="quizAgainBtn">${state.quiz.isReviewMode ? 'Back to Dashboard Review' : 'Try again'}</button><button class="btn btn-ghost" id="quizDashboardBtn">Go to Dashboard</button></div>`; state.xp += xp; state.history.unshift({ label: state.quiz.isReviewMode ? 'Review quiz' : 'Quick quiz', score, timestamp: Date.now() }); state.streak += 1; saveState(); document.getElementById('quizAgainBtn')?.addEventListener('click', () => state.quiz.isReviewMode ? window.setView?.('dashboard') : startQuickQuiz()); document.getElementById('quizDashboardBtn')?.addEventListener('click', () => window.setView?.('dashboard')); state.quiz = null; return; } const progress = state.quiz.questions.map((_, index) => `<span class="dot ${index < state.quiz.current ? 'done' : index === state.quiz.current ? 'current' : ''}"></span>`).join(''); playArea.innerHTML = `<div class="card quiz-stage quiz-question"><div class="quiz-progress">${progress}</div><h3>${escapeHtml(q.q)}</h3><div class="quiz-options">${q.options.map((option, index) => `<button class="quiz-option" data-index="${index}">${escapeHtml(option)}</button>`).join('')}</div><button class="btn btn-ghost btn-sm" id="skipQuizBtn">Skip</button></div>`; playArea.querySelectorAll('.quiz-option').forEach(button => button.addEventListener('click', () => { const pick = Number(button.dataset.index); const correct = pick === q.answer; if (correct) state.quiz.score += 1; else recordIncorrectQuestion(q, pick, q.topic, q.difficulty); playArea.innerHTML = `<div class="card quiz-stage quiz-question"><div class="quiz-progress">${progress}</div><h3>${escapeHtml(q.q)}</h3><div class="quiz-options">${q.options.map((option, index) => `<button class="quiz-option ${index === q.answer ? 'correct' : ''} ${index === pick && !correct ? 'incorrect' : ''}" disabled>${escapeHtml(option)}</button>`).join('')}</div><div class="quiz-feedback ${correct ? '' : 'wrong'}">${correct ? '<strong>✓ Correct!</strong>' : '<strong>✕ Incorrect.</strong>'} ${escapeHtml(q.explain)}</div><button class="btn btn-primary btn-sm" id="nextQuizBtn">${state.quiz.current === state.quiz.questions.length - 1 ? 'Finish' : 'Next question'}</button></div>`; document.getElementById('nextQuizBtn')?.addEventListener('click', () => { state.quiz.current += 1; renderQuiz(); }); })); document.getElementById('skipQuizBtn')?.addEventListener('click', () => { state.quiz.current += 1; renderQuiz(); }); }

export function runAiAdaptiveTest() { startQuickQuiz(); }
